/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package dictionnaire;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pc
 */
public class Home extends java.awt.Frame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(600, 400);
        setResizable(false);
        fillTable();
        setTitle("Dictionnaire");

    }

    private void fillTable() {
        DefaultTableModel model = new DefaultTableModel();

// add the column headers to the model
        model.addColumn("Dictionnaire");
        try {
            String query = "select * from word Dictionnaire";
            java.sql.PreparedStatement ps = ConnectionBDD.getConnection().prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Object[] row = new Object[1];
                row[0] = rs.getString("word");
                model.addRow(row);
            }
            jTable1.setModel(model);

// set the cells as uneditable
            jTable1.setDefaultEditor(Object.class, null);

        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);

        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 260, 200);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 40, 190, 22);

        jRadioButton1.setText("ajouter");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(10, 90, 110, 21);

        jRadioButton2.setText("suprimer");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(130, 90, 98, 21);

        jRadioButton3.setText("mise à jour");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(60, 120, 150, 21);

        jButton1.setText("excuter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 150, 140, 23);

        add(jPanel1);
        jPanel1.setBounds(310, 140, 250, 190);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(40, 80, 130, 22);

        jButton2.setText("verifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(182, 80, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int line = jTable1.getSelectedRow();
        String word = jTable1.getModel().getValueAt(line, 0).toString();
        this.jTextField1.setText(word);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private boolean valideWord(String word) {

        if (word == null || word.isEmpty()) {
            return false;
        }

        if (!word.matches("[a-zA-Z]+")) {
            return false;
        }

        if (word.isEmpty()) {
            return false;
        }

        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String word = jTextField1.getText();
        if (valideWord(word)) {
            WordBDD wordBDD = new WordBDD(word);

            if (jRadioButton1.isSelected()) {
                boolean b = wordBDD.insertWord();
                if (b) {
                    JOptionPane.showMessageDialog(this, "done");
                } else {
                    JOptionPane.showMessageDialog(this, "deja exist");

                }
            }
            if (jRadioButton2.isSelected()) {
                int sure = JOptionPane.showConfirmDialog(this, "are you sure", "Warning", JOptionPane.YES_NO_OPTION);
                if (sure == 0) {
                    boolean b = wordBDD.deleteWord();
                    if (b) {
                        JOptionPane.showMessageDialog(this, "done");
                    } else {
                        JOptionPane.showMessageDialog(this, "deja exist");

                    }
                }
            }
            if (jRadioButton3.isSelected()) {
                int line = jTable1.getSelectedRow();
                if (line != -1) {
                    String old = jTable1.getModel().getValueAt(line, 0).toString();
                    boolean b = wordBDD.updateWord(old);
                    if (b) {
                        JOptionPane.showMessageDialog(this, "done");
                    } else {
                        JOptionPane.showMessageDialog(this, "deja exist");

                    }
                }
            }
            fillTable();
            jTextField1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "donnee un mot valide");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_UP || key == KeyEvent.VK_DOWN) {
            int selectedRow = jTable1.getSelectedRow();
            int rowCount = jTable1.getRowCount();
            if (selectedRow < 0 || selectedRow >= rowCount) {
                return;
            }
            if (key == KeyEvent.VK_UP) {
                selectedRow--;
                if (selectedRow < 0) {
                    selectedRow = rowCount - 1;
                }
            } else if (key == KeyEvent.VK_DOWN) {
                selectedRow++;
                if (selectedRow >= rowCount) {
                    selectedRow = 0;
                }
            }
            jTable1.setRowSelectionInterval(selectedRow, selectedRow);
            this.jTable1MouseClicked(null);
        }
        if (key == KeyEvent.VK_DELETE) {
            int sure = JOptionPane.showConfirmDialog(this, "are you sure", "Warning", JOptionPane.YES_NO_OPTION);
            if (sure == 0) {
                String word = jTextField1.getText();
                WordBDD wordBDD = new WordBDD(word);
                boolean b = wordBDD.deleteWord();
                if (b) {
                    JOptionPane.showMessageDialog(this, "done");
                } else {
                    JOptionPane.showMessageDialog(this, "deja exist");

                }
            }
            fillTable();
            jTextField1.setText("");

        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String query = "select * from word where word like '%" + jTextField2.getText() + "%'";
            java.sql.PreparedStatement ps = ConnectionBDD.getConnection().prepareStatement(query);

            java.sql.ResultSet rs = ps.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if (jTable1.getModel().getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "mot fausse ");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        try {
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (Exception ignored) {
//        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
